// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtoIM96FSOvfImSFAjnrYGxG3_2_ClrQ',
    appId: '1:588834041432:android:9e5477f6ee40c45cd4642d',
    messagingSenderId: '588834041432',
    projectId: 'bola-web-6448f',
    storageBucket: 'bola-web-6448f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxHLWjJhncrEC2jOqadRxmXloWTxlPlA',
    appId: '1:588834041432:ios:a30679108fc3d112d4642d',
    messagingSenderId: '588834041432',
    projectId: 'bola-web-6448f',
    storageBucket: 'bola-web-6448f.firebasestorage.app',
    androidClientId: '588834041432-19psdrobihfqas319bkfpnuk5sau8r3k.apps.googleusercontent.com',
    iosClientId: '588834041432-b10ed930s27hmp8edkuqvog82aav1j5n.apps.googleusercontent.com',
    iosBundleId: 'com.poolmate',
  );

}