// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtoIM96FSOvfImSFAjnrYGxG3_2_ClrQ',
    appId: '1:588834041432:android:b290b55ce8e6513fd4642d',
    messagingSenderId: '588834041432',
    projectId: 'bola-web-6448f',
    storageBucket: 'bola-web-6448f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxHLWjJhncrEC2jOqadRxmXloWTxlPlA',
    appId: '1:588834041432:ios:fd5571b7ae1c8a63d4642d',
    messagingSenderId: '588834041432',
    projectId: 'bola-web-6448f',
    storageBucket: 'bola-web-6448f.firebasestorage.app',
    androidClientId: '588834041432-19psdrobihfqas319bkfpnuk5sau8r3k.apps.googleusercontent.com',
    iosClientId: '588834041432-6kdar449v6ru4llv2kfhc1ccsp2s9prb.apps.googleusercontent.com',
    iosBundleId: 'com.alok.poolmate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOF0WZp3ZTBQc1DxE448eIqGPt42pWL8Y',
    appId: '1:588834041432:web:510ef17ebc132c8ed4642d',
    messagingSenderId: '588834041432',
    projectId: 'bola-web-6448f',
    authDomain: 'bola-web-6448f.firebaseapp.com',
    storageBucket: 'bola-web-6448f.firebasestorage.app',
    measurementId: 'G-QHE2Q8466W',
  );

}